-- MySQL Script generated by MySQL Workbench
-- 11/12/18 17:53:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdGranja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdGranja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdGranja` DEFAULT CHARACTER SET utf8 ;
USE `bdGranja` ;

-- -----------------------------------------------------
-- Table `bdGranja`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`domicilio` (
  `idDomicilio` INT(11) NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT(11) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDomicilio`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`cabaña`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`cabaña` (
  `cuit` VARCHAR(45) NOT NULL,
  `razonSocial` VARCHAR(45) NOT NULL,
  `domicilio` INT(11) NOT NULL,
  PRIMARY KEY (`cuit`),
  INDEX `fk_cabaña_Domicilio1_idx` (`domicilio` ASC),
  CONSTRAINT `fk_cabaña_Domicilio1`
    FOREIGN KEY (`domicilio`)
    REFERENCES `bdGranja`.`domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`cliente` (
  `cuit` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `domicilio` INT(11) NOT NULL,
  PRIMARY KEY (`cuit`),
  INDEX `fk_cliente_Domicilio1_idx` (`domicilio` ASC),
  CONSTRAINT `fk_cliente_Domicilio1`
    FOREIGN KEY (`domicilio`)
    REFERENCES `bdGranja`.`domicilio` (`idDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`factura` (
  `idFactura` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFactura`),
  INDEX `fk_Factura_Cliente1_idx` (`cliente` ASC),
  CONSTRAINT `fk_Factura_Cliente1`
    FOREIGN KEY (`cliente`)
    REFERENCES `bdGranja`.`cliente` (`cuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`genetica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`genetica` (
  `idGenetica` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `cabaña` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenetica`),
  INDEX `fk_Genetica_Cabaña1_idx` (`cabaña` ASC),
  CONSTRAINT `fk_Genetica_Cabaña1`
    FOREIGN KEY (`cabaña`)
    REFERENCES `bdGranja`.`cabaña` (`cuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`plantel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`plantel` (
  `idPlantel` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `edadEntrada` INT(11) NULL DEFAULT NULL,
  `genetica` INT(11) NOT NULL,
  `fechaEntrada` DATE NULL DEFAULT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`idPlantel`),
  INDEX `fk_Plantel_Genetica1_idx` (`genetica` ASC),
  CONSTRAINT `fk_Plantel_Genetica1`
    FOREIGN KEY (`genetica`)
    REFERENCES `bdGranja`.`genetica` (`idGenetica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`galpon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`galpon` (
  `idGalpon` INT(11) NOT NULL,
  `cantidadDeGallinas` INT(11) NULL DEFAULT NULL,
  `plantel` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idGalpon`),
  INDEX `fk_Galpon_Plantel_idx` (`plantel` ASC),
  CONSTRAINT `fk_Galpon_Plantel`
    FOREIGN KEY (`plantel`)
    REFERENCES `bdGranja`.`plantel` (`idPlantel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`planilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`planilla` (
  `idPlanilla` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidadHuevosObtenidos` INT(11) NULL DEFAULT NULL,
  `cantidadGallinasMuertas` INT(11) NULL DEFAULT NULL,
  `cantidadAlimento` FLOAT NULL DEFAULT NULL,
  `tipoAlimento` VARCHAR(45) NULL DEFAULT NULL,
  `galpon` INT(11) NOT NULL,
  `novedades` MEDIUMTEXT NULL,
  PRIMARY KEY (`idPlanilla`),
  INDEX `fk_Planilla_Galpon1_idx` (`galpon` ASC),
  CONSTRAINT `fk_Planilla_Galpon1`
    FOREIGN KEY (`galpon`)
    REFERENCES `bdGranja`.`galpon` (`idGalpon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`producto` (
  `idProducto` INT(11) NOT NULL,
  `precio` FLOAT NULL DEFAULT NULL,
  `cantidad` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`usuario` (
  `cuil` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `legajoInterno` INT NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`cuil`),
  UNIQUE INDEX `legajoInterno_UNIQUE` (`legajoInterno` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdGranja`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`log` (
  `idLog` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `cantidadHuevosObtenidos` INT(11) NULL DEFAULT NULL,
  `cantidadGallinasMuertas` INT(11) NULL DEFAULT NULL,
  `cantidadAlimento` FLOAT NULL DEFAULT NULL,
  `tipoAlimento` VARCHAR(45) NULL DEFAULT NULL,
  `galpon` INT(11) NOT NULL,
  `novedades` MEDIUMTEXT NULL,
  `planilla` INT(11) NOT NULL,
  `fechaModificado` DATE NULL,
  `usuario` INT NOT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `fk_Planilla_Galpon1_idx` (`galpon` ASC),
  INDEX `fk_planilla_copy1_planilla1_idx` (`planilla` ASC),
  INDEX `fk_log_usuario1_idx` (`usuario` ASC),
  CONSTRAINT `fk_Planilla_Galpon10`
    FOREIGN KEY (`galpon`)
    REFERENCES `bdGranja`.`galpon` (`idGalpon`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planilla_copy1_planilla1`
    FOREIGN KEY (`planilla`)
    REFERENCES `bdGranja`.`planilla` (`idPlanilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_log_usuario1`
    FOREIGN KEY (`usuario`)
    REFERENCES `bdGranja`.`usuario` (`cuil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdGranja`.`factura_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdGranja`.`factura_has_producto` (
  `factura` INT(11) NOT NULL,
  `producto` INT(11) NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`factura`, `producto`),
  INDEX `fk_factura_has_producto_producto1_idx` (`producto` ASC),
  INDEX `fk_factura_has_producto_factura1_idx` (`factura` ASC),
  CONSTRAINT `fk_factura_has_producto_factura1`
    FOREIGN KEY (`factura`)
    REFERENCES `bdGranja`.`factura` (`idFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_has_producto_producto1`
    FOREIGN KEY (`producto`)
    REFERENCES `bdGranja`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `bdGranja` ;

-- -----------------------------------------------------
-- procedure agregarCabaña
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarCabaña`(cuit varchar(45), razonSocial varchar(45), calle varchar(45), numero int(11), localidad varchar(45), provincia varchar(45))
BEGIN
declare domicilio int;
if exists(select idDomicilio from domicilio d where d.calle = calle and d.numero = numero and d.localidad = localidad and d.provincia = provincia) then
	set domicilio  = (select idDomicilio from domicilio d where d.calle = calle and d.numero = numero and d.localidad = localidad and d.provincia = provincia);
else
	insert into `bdGranja`.domicilio(`calle`, `numero`, `localidad`, `provincia`)
	values(calle, numero, localidad, provincia);
	set domicilio = (select max(idDomicilio) from domicilio);
end if;
INSERT INTO `bdGranja`.`cabaña` (`cuit`, `razonSocial`, `idDomicillio`) 
VALUES ( cuit, razonSocial, domicilio);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarCliente
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarCliente`(cuit varchar(45), nombre varchar(60), calle varchar(45), numero int(11), localidad varchar(45), provincia varchar(45))
BEGIN
declare domicilio int;
if exists(select idDomicilio from domicilio d where d.calle = calle and d.numero = numero and d.localidad = localidad and d.provincia = provincia) then
	set domicilio  = (select idDomicilio from domicilio d where d.calle = calle and d.numero = numero and d.localidad = localidad and d.provincia = provincia);
else
	insert into `bdGranja`.domicilio(`calle`, `numero`, `localidad`, `provincia`)
	values(calle, numero, localidad, provincia);
	set domicilio = (select max(idDomicilio) from domicilio);
end if;
INSERT INTO `bdGranja`.`cliente` (`cuit`, `nombre`, `idDomicillio`) 
VALUES ( cuit, nombre, domicilio);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarFactura
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarFactura`(fecha date, cantidad int, cuit varchar(45), codigoProducto int)
BEGIN
insert into `bdGranja`.factura(`fecha`, `cantidad`, `cuitCliente`, `codigoProducto`)
values (fecha, cantidad, cuit, codigoProducto);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarGalpon
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarGalpon`(num int, cantGallinas int, codPlantel int)
BEGIN
INSERT INTO `bdGranja`.galpon (numero, cantidadDeGallinas, Plantel_codigo) VALUES (num, cantidadDeGallinas, codPlantel);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarGenetica
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarGenetica`(codigo int(11), nombre varchar(45), cuitCabaña varchar(45))
BEGIN
INSERT INTO `bdGranja`.`genetica`(`codigo`, `nombre`, `Cabaña_cuit`)
VALUES (codigo, nombre, cuitCabaña);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarPlanilla
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarPlanilla`(_fecha date, _cantHuevos int, _cantMuertas int, cantAlimento float, tipoAlimento varchar(45), _numGalpon int)
BEGIN
insert into `bdGranja`.planilla(`fecha`, `cantidadHuevosObtenidos`, `cantidadGallinasMuertas`, `cantidadAlimento`, `tipoAlimento`, `numeroGalpon`)
values (_fecha, _cantHuevos, _cantMuertas, cantAlimento, tipoAlimento, _numGalpon);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarPlantel
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarPlantel`(codigo int(11), nombre varchar(45), edadEntrada int(11), genetica int(11), fechaEntrada date, precio float)
BEGIN
INSERT INTO `bdGranja`.`plantel`(`codigo`, `nombre`, `edadEntrada`, `Genetica_codigo`, `fechaEntrada`, `precio`)
VALUES (codigo, nombre, edadEntrada, genetica, fechaEntrada, precio);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agregarProducto
-- -----------------------------------------------------

DELIMITER $$
USE `bdGranja`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agregarProducto`(codigo int, precio float, cantidad int)
BEGIN
insert into `bdGranja`.producto(`codigo`, `precio`, `cantidad`)
values(codigo, precio, cantidad);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
